# Generated by Django 3.2.6 on 2021-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='краска')),
                ('qty', models.IntegerField(verbose_name='количество коробок')),
                ('color', models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый')], default='red', max_length=10, verbose_name='цвет')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('date_of_upload', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('piece', 'штука'), ('kilo', 'килограмм'), ('litr', 'литр')], default='piece', max_length=10, verbose_name='единица'),
        ),
    ]
